#Kernel location

TOPDIR 	?= $(shell pwd)/../../..
KERNELDIR ?= $(TOPDIR)/kernel
PLATDIR ?= $(TOPDIR)/platform



# Flags

INCLUDE    =	-I. \
		-I$(KERNELDIR)/include \
		-I$(KERNELDIR)/include/driver \
		-I$(PLATDIR)/libplat/include \
		-I$(PLATDIR)/libmpi/include \
		-I$(PLATDIR)/libapp/include \
		-I$(PLATDIR)/apps/config \
		-I$(PLATDIR)/apps/video \
		-I$(PLATDIR)/apps/audio \
		-I$(PLATDIR)/apps/spi_cmd \
		-I$(PLATDIR)/apps/ringbuffer \
		-I$(PLATDIR)/apps/spi_layer \
		-I$(PLATDIR)/apps/scheduler_layer \


#Src locations
BUILDPATH  ?= build

SRCDIR += .

CSRCS += $(foreach d, $(SRCDIR), $(wildcard $d/*.c))

COBJS += $(patsubst %.c, $(BUILDPATH)/%.o, $(CSRCS))



#build rule
.PHONY: all prepare target clean

all: prepare target 

prepare:
ifneq ($(BUILDPATH),)
	@for i in $(SRCDIR); \
	do mkdir -p $(BUILDPATH)/$$i; \
	done
endif


target: $(COBJS) 
	@echo ---------------------[build obj complete]----------------------------------	


clean : 
	$(RM) $(BUILDPATH)


# Rules
include $(TOPDIR)/rules.mk

